### PR TITLE
New parameter request

### PR DESCRIPTION
**Pull request by ghost**
Can you add a parameter to not change a pixel if the change is lower than the passed value to keep low frequency safe?

### CODE REVIEW

**Comment by Asd-g** [comment]
This is a just request (not pull request), right?

**Comment by kedaitinh12** [comment]
> Can you add a parameter to not change a pixel if the change is lower than the passed value to keep low frequency safe?

I think you just request function in Issues tab

**Comment by ghost** [comment]
> I think you just request function in Issues

Sorry, I'm new to this GitHub stuff, where I'm supposed to ask for it?
> This is a just request (not pull request), right?

Yes, is not a pull request... sorry, as I said I just subscribed and I don't know how this site works, sorry if I caused trouble :)

**Comment by kedaitinh12** [comment]
> > I think you just request function in Issues
> 
> Sorry, I'm new to this GitHub stuff, where I'm supposed to ask for it?

here
https://github.com/Asd-g/vinverse/issues

**Comment by Asd-g** [comment]
@CeppoTools, wouldn't mt_binarize do what you want?

**Comment by ghost** [comment]
@Asd-g 
If I use masktools I have to do the check after the sharpening, if you implement it, you can do it on the blurred clip. That's why I'm asking.

**Comment by Asd-g** [comment]
Ok, I will do it.

**Comment by ghost** [comment]
Thanks a lot :)

**Comment by Asd-g** [comment]
Please try the attached test version. `thr` parameter is added (default 0 - no threshold).

[vinverse.zip](https://github.com/Asd-g/vinverse/files/8385162/vinverse.zip)

**Comment by ghost** [comment]
Something is off, vinverse(0,thr=64) saves next to no detail while vinverse(0,thr=0).mt_lutxy(last,"x y - abs 12 < y x ?",u=3,v=3) almost gives the original picture. Since I'm using sstr=0, they should give the same output.

**Comment by Asd-g** [comment]
`vinverse(0,thr=64)` should be the same as `vinverse(0,thr=0).mt_lutxy(last,"x 64 < y x ?",u=3,v=3)`.

**Comment by ghost** [comment]
Sorry, I was not clear enough I meant to implement this vinverse(0,thr=0).mt_lutxy(last,"x y - abs "+string(thr)+" < y x ?",u=3,v=3) since I want to preserve low frequency (grain, texture on a wall, things like that), so if there is not much difference from the blurred clip it is a low frequency, if there is a lot of difference it is a high frequency, that's what I meant. I'm really sorry I was not clear enough, of course you can't read my mind, I thought "low frequency" was a standard way to refer to that kind of detail.

**Comment by Asd-g** [comment]
Please try the attached versions. Both should give same output.

[vinverse.zip](https://github.com/Asd-g/vinverse/files/8393496/vinverse.zip)

**Comment by ghost** [comment]
Thanks, both seem to give the expected result.
mt_makediff(vinverse(0,thr=12),vinverse(0,thr=0).mt_lutxy(last,"x y - abs 12 < y x ?",u=3,v=3),u=3,v=3)
gives perfect 128 on all pixels.

**Pull request closed without merging**
